apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kg1f6ziqi-java-quarkus
  janus-idp.io/tekton: kg1f6ziqi-java-quarkus
  backstage.io/kubernetes-id: kg1f6ziqi-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kg1f6ziqi-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
